// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "stringer -bitset -type ParamPropBits"; DO NOT EDIT.

package inlheur

func (i ParamPropBits) String() string
