// Code generated by mknode.go. DO NOT EDIT.

package ir

import "github.com/shogo82148/std/fmt"

func (n *AddStringExpr) Format(s fmt.State, verb rune)

func (n *AddrExpr) Format(s fmt.State, verb rune)

func (n *AssignListStmt) Format(s fmt.State, verb rune)

func (n *AssignOpStmt) Format(s fmt.State, verb rune)

func (n *AssignStmt) Format(s fmt.State, verb rune)

func (n *BasicLit) Format(s fmt.State, verb rune)

func (n *BinaryExpr) Format(s fmt.State, verb rune)

func (n *BlockStmt) Format(s fmt.State, verb rune)

func (n *BranchStmt) Format(s fmt.State, verb rune)

func (n *CallExpr) Format(s fmt.State, verb rune)

func (n *CaseClause) Format(s fmt.State, verb rune)

func (n *ClosureExpr) Format(s fmt.State, verb rune)

func (n *CommClause) Format(s fmt.State, verb rune)

func (n *CompLitExpr) Format(s fmt.State, verb rune)

func (n *ConstExpr) Format(s fmt.State, verb rune)

func (n *ConvExpr) Format(s fmt.State, verb rune)

func (n *Decl) Format(s fmt.State, verb rune)

func (n *DynamicType) Format(s fmt.State, verb rune)

func (n *DynamicTypeAssertExpr) Format(s fmt.State, verb rune)

func (n *ForStmt) Format(s fmt.State, verb rune)

func (n *Func) Format(s fmt.State, verb rune)

func (n *GoDeferStmt) Format(s fmt.State, verb rune)

func (n *Ident) Format(s fmt.State, verb rune)

func (n *IfStmt) Format(s fmt.State, verb rune)

func (n *IndexExpr) Format(s fmt.State, verb rune)

func (n *InlineMarkStmt) Format(s fmt.State, verb rune)

func (n *InlinedCallExpr) Format(s fmt.State, verb rune)

func (n *InstExpr) Format(s fmt.State, verb rune)

func (n *JumpTableStmt) Format(s fmt.State, verb rune)

func (n *KeyExpr) Format(s fmt.State, verb rune)

func (n *LabelStmt) Format(s fmt.State, verb rune)

func (n *LinksymOffsetExpr) Format(s fmt.State, verb rune)

func (n *LogicalExpr) Format(s fmt.State, verb rune)

func (n *MakeExpr) Format(s fmt.State, verb rune)

func (n *Name) Format(s fmt.State, verb rune)

func (n *NilExpr) Format(s fmt.State, verb rune)

func (n *ParenExpr) Format(s fmt.State, verb rune)

func (n *RangeStmt) Format(s fmt.State, verb rune)

func (n *RawOrigExpr) Format(s fmt.State, verb rune)

func (n *ResultExpr) Format(s fmt.State, verb rune)

func (n *ReturnStmt) Format(s fmt.State, verb rune)

func (n *SelectStmt) Format(s fmt.State, verb rune)

func (n *SelectorExpr) Format(s fmt.State, verb rune)

func (n *SendStmt) Format(s fmt.State, verb rune)

func (n *SliceExpr) Format(s fmt.State, verb rune)

func (n *SliceHeaderExpr) Format(s fmt.State, verb rune)

func (n *StarExpr) Format(s fmt.State, verb rune)

func (n *StringHeaderExpr) Format(s fmt.State, verb rune)

func (n *StructKeyExpr) Format(s fmt.State, verb rune)

func (n *SwitchStmt) Format(s fmt.State, verb rune)

func (n *TailCallStmt) Format(s fmt.State, verb rune)

func (n *TypeAssertExpr) Format(s fmt.State, verb rune)

func (n *TypeSwitchGuard) Format(s fmt.State, verb rune)

func (n *UnaryExpr) Format(s fmt.State, verb rune)
