// Code generated by "stringer -linecomment -type=SignatureScheme,CurveID,ClientAuthType -output=common_string.go"; DO NOT EDIT.

package tls

func (i SignatureScheme) String() string

func (i CurveID) String() string

func (i ClientAuthType) String() string
