// Code generated by 'go run -C $GOROOT/src/simd/archsimd/_gen/midway'; DO NOT EDIT.

//go:build goexperiment.simd

// Scalable vector types for rewriting and emulation

package simd

// Int8s represents a vector of 8-bit signed integers.
type Int8s struct {
	_    _simd
	a, b uint64
}

// Int16s represents a vector of 16-bit signed integers.
type Int16s struct {
	_    _simd
	a, b uint64
}

// Int32s represents a vector of 32-bit signed integers.
type Int32s struct {
	_    _simd
	a, b uint64
}

// Int64s represents a vector of 64-bit signed integers.
type Int64s struct {
	_    _simd
	a, b uint64
}

// Uint8s represents a vector of 8-bit unsigned integers.
type Uint8s struct {
	_    _simd
	a, b uint64
}

// Uint16s represents a vector of 16-bit unsigned integers.
type Uint16s struct {
	_    _simd
	a, b uint64
}

// Uint32s represents a vector of 32-bit unsigned integers.
type Uint32s struct {
	_    _simd
	a, b uint64
}

// Uint64s represents a vector of 64-bit unsigned integers.
type Uint64s struct {
	_    _simd
	a, b uint64
}

// Float32s represents a vector of 32-bit floating-point numbers.
type Float32s struct {
	_    _simd
	a, b uint64
}

// Float64s represents a vector of 64-bit floating-point numbers.
type Float64s struct {
	_    _simd
	a, b uint64
}

// Mask8s represents a boolean mask for Int8s/Uint8s vectors.
type Mask8s struct {
	_    _simd
	a, b uint64
}

// Mask16s represents a boolean mask for Int16s/Uint16s vectors.
type Mask16s struct {
	_    _simd
	a, b uint64
}

// Mask32s represents a boolean mask for Int32s/Uint32s vectors.
type Mask32s struct {
	_    _simd
	a, b uint64
}

// Mask64s represents a boolean mask for Int64s/Uint64s vectors.
type Mask64s struct {
	_    _simd
	a, b uint64
}
