// Code generated by 'go run -C $GOROOT/src/simd/archsimd/_gen/midway'; DO NOT EDIT.

//go:build goexperiment.simd && amd64

package simd

func (x Int8s) ToArch() any

func Int8sFromArch[T archSimdInt8s](x T) Int8s

func (x Int16s) ToArch() any

func Int16sFromArch[T archSimdInt16s](x T) Int16s

func (x Int32s) ToArch() any

func Int32sFromArch[T archSimdInt32s](x T) Int32s

func (x Int64s) ToArch() any

func Int64sFromArch[T archSimdInt64s](x T) Int64s

func (x Uint8s) ToArch() any

func Uint8sFromArch[T archSimdUint8s](x T) Uint8s

func (x Uint16s) ToArch() any

func Uint16sFromArch[T archSimdUint16s](x T) Uint16s

func (x Uint32s) ToArch() any

func Uint32sFromArch[T archSimdUint32s](x T) Uint32s

func (x Uint64s) ToArch() any

func Uint64sFromArch[T archSimdUint64s](x T) Uint64s

func (x Float32s) ToArch() any

func Float32sFromArch[T archSimdFloat32s](x T) Float32s

func (x Float64s) ToArch() any

func Float64sFromArch[T archSimdFloat64s](x T) Float64s

func (x Mask8s) ToArch() any

func Mask8sFromArch[T archSimdMask8s](x T) Mask8s

func (x Mask16s) ToArch() any

func Mask16sFromArch[T archSimdMask16s](x T) Mask16s

func (x Mask32s) ToArch() any

func Mask32sFromArch[T archSimdMask32s](x T) Mask32s

func (x Mask64s) ToArch() any

func Mask64sFromArch[T archSimdMask64s](x T) Mask64s
