// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Int8x16) Masked(mask Mask8x16) (z Int8x16)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Int8x16) IfElse(mask Mask8x16, y Int8x16) (z Int8x16)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Int16x8) Masked(mask Mask16x8) (z Int16x8)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Int16x8) IfElse(mask Mask16x8, y Int16x8) (z Int16x8)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Int32x4) Masked(mask Mask32x4) (z Int32x4)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Int32x4) IfElse(mask Mask32x4, y Int32x4) (z Int32x4)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Int64x2) Masked(mask Mask64x2) (z Int64x2)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Int64x2) IfElse(mask Mask64x2, y Int64x2) (z Int64x2)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Uint8x16) Masked(mask Mask8x16) (z Uint8x16)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Uint8x16) IfElse(mask Mask8x16, y Uint8x16) (z Uint8x16)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Uint16x8) Masked(mask Mask16x8) (z Uint16x8)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Uint16x8) IfElse(mask Mask16x8, y Uint16x8) (z Uint16x8)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Uint32x4) Masked(mask Mask32x4) (z Uint32x4)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Uint32x4) IfElse(mask Mask32x4, y Uint32x4) (z Uint32x4)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Uint64x2) Masked(mask Mask64x2) (z Uint64x2)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Uint64x2) IfElse(mask Mask64x2, y Uint64x2) (z Uint64x2)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Float32x4) Masked(mask Mask32x4) (z Float32x4)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Float32x4) IfElse(mask Mask32x4, y Float32x4) (z Float32x4)

// Masked returns a vector with elements from x where mask is true, and zero
// elsewhere.
//
//	z[i] = if mask[i] { x[i] } else { 0 }
func (x Float64x2) Masked(mask Mask64x2) (z Float64x2)

// IfElse returns a vector with elements from x where mask is true, and y where
// mask is false.
//
//	z[i] = if mask[i] { x[i] } else { y[i] }
func (x Float64x2) IfElse(mask Mask64x2, y Float64x2) (z Float64x2)

// String returns a string representation of SIMD mask x.
func (x Mask8x16) String() string

// String returns a string representation of SIMD mask x.
func (x Mask16x8) String() string

// String returns a string representation of SIMD mask x.
func (x Mask32x4) String() string

// String returns a string representation of SIMD mask x.
func (x Mask64x2) String() string
