// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// Masked returns x but with elements zeroed where mask is false.
func (x Int8x16) Masked(mask Mask8x16) Int8x16

// IfElse returns x but with elements set to y where mask is false.
func (x Int8x16) IfElse(mask Mask8x16, y Int8x16) Int8x16

// Masked returns x but with elements zeroed where mask is false.
func (x Int16x8) Masked(mask Mask16x8) Int16x8

// IfElse returns x but with elements set to y where mask is false.
func (x Int16x8) IfElse(mask Mask16x8, y Int16x8) Int16x8

// Masked returns x but with elements zeroed where mask is false.
func (x Int32x4) Masked(mask Mask32x4) Int32x4

// IfElse returns x but with elements set to y where mask is false.
func (x Int32x4) IfElse(mask Mask32x4, y Int32x4) Int32x4

// Masked returns x but with elements zeroed where mask is false.
func (x Int64x2) Masked(mask Mask64x2) Int64x2

// IfElse returns x but with elements set to y where mask is false.
func (x Int64x2) IfElse(mask Mask64x2, y Int64x2) Int64x2

// Masked returns x but with elements zeroed where mask is false.
func (x Uint8x16) Masked(mask Mask8x16) Uint8x16

// IfElse returns x but with elements set to y where mask is false.
func (x Uint8x16) IfElse(mask Mask8x16, y Uint8x16) Uint8x16

// Masked returns x but with elements zeroed where mask is false.
func (x Uint16x8) Masked(mask Mask16x8) Uint16x8

// IfElse returns x but with elements set to y where mask is false.
func (x Uint16x8) IfElse(mask Mask16x8, y Uint16x8) Uint16x8

// Masked returns x but with elements zeroed where mask is false.
func (x Uint32x4) Masked(mask Mask32x4) Uint32x4

// IfElse returns x but with elements set to y where mask is false.
func (x Uint32x4) IfElse(mask Mask32x4, y Uint32x4) Uint32x4

// Masked returns x but with elements zeroed where mask is false.
func (x Uint64x2) Masked(mask Mask64x2) Uint64x2

// IfElse returns x but with elements set to y where mask is false.
func (x Uint64x2) IfElse(mask Mask64x2, y Uint64x2) Uint64x2

// Masked returns x but with elements zeroed where mask is false.
func (x Float32x4) Masked(mask Mask32x4) Float32x4

// IfElse returns x but with elements set to y where mask is false.
func (x Float32x4) IfElse(mask Mask32x4, y Float32x4) Float32x4

// Masked returns x but with elements zeroed where mask is false.
func (x Float64x2) Masked(mask Mask64x2) Float64x2

// IfElse returns x but with elements set to y where mask is false.
func (x Float64x2) IfElse(mask Mask64x2, y Float64x2) Float64x2

// String returns a string representation of SIMD mask x.
func (x Mask8x16) String() string

// String returns a string representation of SIMD mask x.
func (x Mask16x8) String() string

// String returns a string representation of SIMD mask x.
func (x Mask32x4) String() string

// String returns a string representation of SIMD mask x.
func (x Mask64x2) String() string
