// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// BroadcastInt8x16 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastInt8x16(x int8) Int8x16

// BroadcastInt16x8 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastInt16x8(x int16) Int16x8

// BroadcastInt32x4 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastInt32x4(x int32) Int32x4

// BroadcastInt64x2 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastInt64x2(x int64) Int64x2

// BroadcastUint8x16 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastUint8x16(x uint8) Uint8x16

// BroadcastUint16x8 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastUint16x8(x uint16) Uint16x8

// BroadcastUint32x4 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastUint32x4(x uint32) Uint32x4

// BroadcastUint64x2 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastUint64x2(x uint64) Uint64x2

// BroadcastFloat32x4 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastFloat32x4(x float32) Float32x4

// BroadcastFloat64x2 returns a vector with the input
// x assigned to all elements of the output.
func BroadcastFloat64x2(x float64) Float64x2

// String returns a string representation of SIMD vector x.
func (x Int8x16) String() string

// String returns a string representation of SIMD vector x.
func (x Int16x8) String() string

// String returns a string representation of SIMD vector x.
func (x Int32x4) String() string

// String returns a string representation of SIMD vector x.
func (x Int64x2) String() string

// String returns a string representation of SIMD vector x.
func (x Uint8x16) String() string

// String returns a string representation of SIMD vector x.
func (x Uint16x8) String() string

// String returns a string representation of SIMD vector x.
func (x Uint32x4) String() string

// String returns a string representation of SIMD vector x.
func (x Uint64x2) String() string

// String returns a string representation of SIMD vector x.
func (x Float32x4) String() string

// String returns a string representation of SIMD vector x.
func (x Float64x2) String() string

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Int8x16) HiToLo() Int8x16

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Int16x8) HiToLo() Int16x8

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Int32x4) HiToLo() Int32x4

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Int64x2) HiToLo() Int64x2

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Uint8x16) HiToLo() Uint8x16

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Uint16x8) HiToLo() Uint16x8

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Uint32x4) HiToLo() Uint32x4

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Uint64x2) HiToLo() Uint64x2

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Float32x4) HiToLo() Float32x4

// HiToLo returns a vector with the upper 64 bits zeroed and the lower
// 64 bits replaced with the upper 64 bits of x.
func (x Float64x2) HiToLo() Float64x2

// ToMask returns a mask whose i'th element is set if x[i] is non-zero.
func (from Int8x16) ToMask() (to Mask8x16)

// ToMask returns a mask whose i'th element is set if x[i] is non-zero.
func (from Int16x8) ToMask() (to Mask16x8)

// ToMask returns a mask whose i'th element is set if x[i] is non-zero.
func (from Int32x4) ToMask() (to Mask32x4)

// ToMask returns a mask whose i'th element is set if x[i] is non-zero.
func (from Int64x2) ToMask() (to Mask64x2)

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Int8x16) RotateAllLeft(dist uint64) Int8x16

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Int8x16) RotateAllRight(dist uint64) Int8x16

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Int16x8) RotateAllLeft(dist uint64) Int16x8

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Int16x8) RotateAllRight(dist uint64) Int16x8

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Int32x4) RotateAllLeft(dist uint64) Int32x4

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Int32x4) RotateAllRight(dist uint64) Int32x4

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Int64x2) RotateAllLeft(dist uint64) Int64x2

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Int64x2) RotateAllRight(dist uint64) Int64x2

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Uint8x16) RotateAllLeft(dist uint64) Uint8x16

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Uint8x16) RotateAllRight(dist uint64) Uint8x16

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Uint16x8) RotateAllLeft(dist uint64) Uint16x8

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Uint16x8) RotateAllRight(dist uint64) Uint16x8

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Uint32x4) RotateAllLeft(dist uint64) Uint32x4

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Uint32x4) RotateAllRight(dist uint64) Uint32x4

// RotateAllLeft rotates all elements left by the specified amount
//
// Emulated
func (x Uint64x2) RotateAllLeft(dist uint64) Uint64x2

// RotateAllRight rotates all elements right by the specified amount
//
// Emulated
func (x Uint64x2) RotateAllRight(dist uint64) Uint64x2

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Int8x16) ReduceSum() int8

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Int16x8) ReduceSum() int16

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Int32x4) ReduceSum() int32

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint8x16) ReduceSum() uint8

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint16x8) ReduceSum() uint16

// ReduceSum reduces x by summing all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint32x4) ReduceSum() uint32

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int8x16) ReduceMax() int8

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int8x16) ReduceMin() int8

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int16x8) ReduceMax() int16

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int16x8) ReduceMin() int16

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int32x4) ReduceMax() int32

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Int32x4) ReduceMin() int32

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint8x16) ReduceMax() uint8

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint8x16) ReduceMin() uint8

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint16x8) ReduceMax() uint16

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint16x8) ReduceMin() uint16

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint32x4) ReduceMax() uint32

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Uint32x4) ReduceMin() uint32

// ReduceMax reduces x by taking the maximum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Float32x4) ReduceMax() float32

// ReduceMin reduces x by taking the minimum of all elements.
//
// Emulated, CPU Feature: NEON
func (x Float32x4) ReduceMin() float32
