// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// LoadInt8x16 loads an Int8x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadInt8x16(s []int8) Int8x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Int8x16) Store(s []int8)

// LoadInt16x8 loads an Int16x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadInt16x8(s []int16) Int16x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Int16x8) Store(s []int16)

// LoadInt32x4 loads an Int32x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadInt32x4(s []int32) Int32x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Int32x4) Store(s []int32)

// LoadInt64x2 loads an Int64x2 from a slice of elements.
// If s does not have at least 2 elements, it panics.
func LoadInt64x2(s []int64) Int64x2

// Store stores the elements of x into a slice.
// If s does not have at least 2 elements, it panics.
func (x Int64x2) Store(s []int64)

// LoadUint8x16 loads an Uint8x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadUint8x16(s []uint8) Uint8x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Uint8x16) Store(s []uint8)

// LoadUint16x8 loads an Uint16x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadUint16x8(s []uint16) Uint16x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Uint16x8) Store(s []uint16)

// LoadUint32x4 loads an Uint32x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadUint32x4(s []uint32) Uint32x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Uint32x4) Store(s []uint32)

// LoadUint64x2 loads an Uint64x2 from a slice of elements.
// If s does not have at least 2 elements, it panics.
func LoadUint64x2(s []uint64) Uint64x2

// Store stores the elements of x into a slice.
// If s does not have at least 2 elements, it panics.
func (x Uint64x2) Store(s []uint64)

// LoadFloat32x4 loads a Float32x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadFloat32x4(s []float32) Float32x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Float32x4) Store(s []float32)

// LoadFloat64x2 loads a Float64x2 from a slice of elements.
// If s does not have at least 2 elements, it panics.
func LoadFloat64x2(s []float64) Float64x2

// Store stores the elements of x into a slice.
// If s does not have at least 2 elements, it panics.
func (x Float64x2) Store(s []float64)

// LoadInt8x32 loads an Int8x32 from a slice of elements.
// If s does not have at least 32 elements, it panics.
func LoadInt8x32(s []int8) Int8x32

// Store stores the elements of x into a slice.
// If s does not have at least 32 elements, it panics.
func (x Int8x32) Store(s []int8)

// LoadInt16x16 loads an Int16x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadInt16x16(s []int16) Int16x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Int16x16) Store(s []int16)

// LoadInt32x8 loads an Int32x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadInt32x8(s []int32) Int32x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Int32x8) Store(s []int32)

// LoadInt64x4 loads an Int64x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadInt64x4(s []int64) Int64x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Int64x4) Store(s []int64)

// LoadUint8x32 loads an Uint8x32 from a slice of elements.
// If s does not have at least 32 elements, it panics.
func LoadUint8x32(s []uint8) Uint8x32

// Store stores the elements of x into a slice.
// If s does not have at least 32 elements, it panics.
func (x Uint8x32) Store(s []uint8)

// LoadUint16x16 loads an Uint16x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadUint16x16(s []uint16) Uint16x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Uint16x16) Store(s []uint16)

// LoadUint32x8 loads an Uint32x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadUint32x8(s []uint32) Uint32x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Uint32x8) Store(s []uint32)

// LoadUint64x4 loads an Uint64x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadUint64x4(s []uint64) Uint64x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Uint64x4) Store(s []uint64)

// LoadFloat32x8 loads a Float32x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadFloat32x8(s []float32) Float32x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Float32x8) Store(s []float32)

// LoadFloat64x4 loads a Float64x4 from a slice of elements.
// If s does not have at least 4 elements, it panics.
func LoadFloat64x4(s []float64) Float64x4

// Store stores the elements of x into a slice.
// If s does not have at least 4 elements, it panics.
func (x Float64x4) Store(s []float64)

// LoadInt8x64 loads an Int8x64 from a slice of elements.
// If s does not have at least 64 elements, it panics.
func LoadInt8x64(s []int8) Int8x64

// Store stores the elements of x into a slice.
// If s does not have at least 64 elements, it panics.
func (x Int8x64) Store(s []int8)

// LoadInt16x32 loads an Int16x32 from a slice of elements.
// If s does not have at least 32 elements, it panics.
func LoadInt16x32(s []int16) Int16x32

// Store stores the elements of x into a slice.
// If s does not have at least 32 elements, it panics.
func (x Int16x32) Store(s []int16)

// LoadInt32x16 loads an Int32x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadInt32x16(s []int32) Int32x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Int32x16) Store(s []int32)

// LoadInt64x8 loads an Int64x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadInt64x8(s []int64) Int64x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Int64x8) Store(s []int64)

// LoadUint8x64 loads an Uint8x64 from a slice of elements.
// If s does not have at least 64 elements, it panics.
func LoadUint8x64(s []uint8) Uint8x64

// Store stores the elements of x into a slice.
// If s does not have at least 64 elements, it panics.
func (x Uint8x64) Store(s []uint8)

// LoadUint16x32 loads an Uint16x32 from a slice of elements.
// If s does not have at least 32 elements, it panics.
func LoadUint16x32(s []uint16) Uint16x32

// Store stores the elements of x into a slice.
// If s does not have at least 32 elements, it panics.
func (x Uint16x32) Store(s []uint16)

// LoadUint32x16 loads an Uint32x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadUint32x16(s []uint32) Uint32x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Uint32x16) Store(s []uint32)

// LoadUint64x8 loads an Uint64x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadUint64x8(s []uint64) Uint64x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Uint64x8) Store(s []uint64)

// LoadFloat32x16 loads a Float32x16 from a slice of elements.
// If s does not have at least 16 elements, it panics.
func LoadFloat32x16(s []float32) Float32x16

// Store stores the elements of x into a slice.
// If s does not have at least 16 elements, it panics.
func (x Float32x16) Store(s []float32)

// LoadFloat64x8 loads a Float64x8 from a slice of elements.
// If s does not have at least 8 elements, it panics.
func LoadFloat64x8(s []float64) Float64x8

// Store stores the elements of x into a slice.
// If s does not have at least 8 elements, it panics.
func (x Float64x8) Store(s []float64)

// LoadInt8x64Part loads a Int8x64 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 64 elements, the remaining elements of the vector are filled with zeroes.
// If s has 64 or more elements, the function is equivalent to LoadInt8x64.
func LoadInt8x64Part(s []int8) (Int8x64, int)

// StorePart stores the 64 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 64 or more elements, the method is equivalent to x.Store.
func (x Int8x64) StorePart(s []int8) int

// LoadInt16x32Part loads a Int16x32 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 32 elements, the remaining elements of the vector are filled with zeroes.
// If s has 32 or more elements, the function is equivalent to LoadInt16x32.
func LoadInt16x32Part(s []int16) (Int16x32, int)

// StorePart stores the 32 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 32 or more elements, the method is equivalent to x.Store.
func (x Int16x32) StorePart(s []int16) int

// LoadInt32x16Part loads a Int32x16 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 16 elements, the remaining elements of the vector are filled with zeroes.
// If s has 16 or more elements, the function is equivalent to LoadInt32x16.
func LoadInt32x16Part(s []int32) (Int32x16, int)

// StorePart stores the 16 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 16 or more elements, the method is equivalent to x.Store.
func (x Int32x16) StorePart(s []int32) int

// LoadInt64x8Part loads a Int64x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadInt64x8.
func LoadInt64x8Part(s []int64) (Int64x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Int64x8) StorePart(s []int64) int

// LoadUint8x64Part loads a Uint8x64 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 64 elements, the remaining elements of the vector are filled with zeroes.
// If s has 64 or more elements, the function is equivalent to LoadUint8x64.
func LoadUint8x64Part(s []uint8) (Uint8x64, int)

// StorePart stores the 64 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 64 or more elements, the method is equivalent to x.Store.
func (x Uint8x64) StorePart(s []uint8) int

// LoadUint16x32Part loads a Uint16x32 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 32 elements, the remaining elements of the vector are filled with zeroes.
// If s has 32 or more elements, the function is equivalent to LoadUint16x32.
func LoadUint16x32Part(s []uint16) (Uint16x32, int)

// StorePart stores the 32 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 32 or more elements, the method is equivalent to x.Store.
func (x Uint16x32) StorePart(s []uint16) int

// LoadUint32x16Part loads a Uint32x16 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 16 elements, the remaining elements of the vector are filled with zeroes.
// If s has 16 or more elements, the function is equivalent to LoadUint32x16.
func LoadUint32x16Part(s []uint32) (Uint32x16, int)

// StorePart stores the 16 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 16 or more elements, the method is equivalent to x.Store.
func (x Uint32x16) StorePart(s []uint32) int

// LoadUint64x8Part loads a Uint64x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadUint64x8.
func LoadUint64x8Part(s []uint64) (Uint64x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Uint64x8) StorePart(s []uint64) int

// LoadFloat32x16Part loads a Float32x16 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 16 elements, the remaining elements of the vector are filled with zeroes.
// If s has 16 or more elements, the function is equivalent to LoadFloat32x16.
func LoadFloat32x16Part(s []float32) (Float32x16, int)

// StorePart stores the 16 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 16 or more elements, the method is equivalent to x.Store.
func (x Float32x16) StorePart(s []float32) int

// LoadFloat64x8Part loads a Float64x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadFloat64x8.
func LoadFloat64x8Part(s []float64) (Float64x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Float64x8) StorePart(s []float64) int

// LoadInt32x4Part loads a Int32x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadInt32x4.
func LoadInt32x4Part(s []int32) (Int32x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Int32x4) StorePart(s []int32) int

// LoadInt64x2Part loads a Int64x2 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 2 elements, the remaining elements of the vector are filled with zeroes.
// If s has 2 or more elements, the function is equivalent to LoadInt64x2.
func LoadInt64x2Part(s []int64) (Int64x2, int)

// StorePart stores the 2 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 2 or more elements, the method is equivalent to x.Store.
func (x Int64x2) StorePart(s []int64) int

// LoadUint32x4Part loads a Uint32x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadUint32x4.
func LoadUint32x4Part(s []uint32) (Uint32x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Uint32x4) StorePart(s []uint32) int

// LoadUint64x2Part loads a Uint64x2 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 2 elements, the remaining elements of the vector are filled with zeroes.
// If s has 2 or more elements, the function is equivalent to LoadUint64x2.
func LoadUint64x2Part(s []uint64) (Uint64x2, int)

// StorePart stores the 2 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 2 or more elements, the method is equivalent to x.Store.
func (x Uint64x2) StorePart(s []uint64) int

// LoadFloat32x4Part loads a Float32x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadFloat32x4.
func LoadFloat32x4Part(s []float32) (Float32x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Float32x4) StorePart(s []float32) int

// LoadFloat64x2Part loads a Float64x2 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 2 elements, the remaining elements of the vector are filled with zeroes.
// If s has 2 or more elements, the function is equivalent to LoadFloat64x2.
func LoadFloat64x2Part(s []float64) (Float64x2, int)

// StorePart stores the 2 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 2 or more elements, the method is equivalent to x.Store.
func (x Float64x2) StorePart(s []float64) int

// LoadInt32x8Part loads a Int32x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadInt32x8.
func LoadInt32x8Part(s []int32) (Int32x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Int32x8) StorePart(s []int32) int

// LoadInt64x4Part loads a Int64x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadInt64x4.
func LoadInt64x4Part(s []int64) (Int64x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Int64x4) StorePart(s []int64) int

// LoadUint32x8Part loads a Uint32x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadUint32x8.
func LoadUint32x8Part(s []uint32) (Uint32x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Uint32x8) StorePart(s []uint32) int

// LoadUint64x4Part loads a Uint64x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadUint64x4.
func LoadUint64x4Part(s []uint64) (Uint64x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Uint64x4) StorePart(s []uint64) int

// LoadFloat32x8Part loads a Float32x8 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 8 elements, the remaining elements of the vector are filled with zeroes.
// If s has 8 or more elements, the function is equivalent to LoadFloat32x8.
func LoadFloat32x8Part(s []float32) (Float32x8, int)

// StorePart stores the 8 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 8 or more elements, the method is equivalent to x.Store.
func (x Float32x8) StorePart(s []float32) int

// LoadFloat64x4Part loads a Float64x4 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 4 elements, the remaining elements of the vector are filled with zeroes.
// If s has 4 or more elements, the function is equivalent to LoadFloat64x4.
func LoadFloat64x4Part(s []float64) (Float64x4, int)

// StorePart stores the 4 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 4 or more elements, the method is equivalent to x.Store.
func (x Float64x4) StorePart(s []float64) int

// LoadUint8x32Part loads a Uint8x32 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 32 elements, the remaining elements of the vector are filled with zeroes.
// If s has 32 or more elements, the function is equivalent to LoadUint8x32.
func LoadUint8x32Part(s []uint8) (Uint8x32, int)

// StorePart stores the 32 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 32 or more elements, the method is equivalent to x.Store.
func (x Uint8x32) StorePart(s []uint8) int

// LoadUint16x16Part loads a Uint16x16 from the slice s, it returns the loaded vector and the
// number of elements loaded.
// If s has fewer than 16 elements, the remaining elements of the vector are filled with zeroes.
// If s has 16 or more elements, the function is equivalent to LoadUint16x16.
func LoadUint16x16Part(s []uint16) (Uint16x16, int)

// StorePart stores the 16 elements of x into the slice s.
// It stores as many elements as will fit in s.
// If s has 16 or more elements, the method is equivalent to x.Store.
func (x Uint16x16) StorePart(s []uint16) int
