// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// LoadInt8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadInt8x16(s []int8) (z Int8x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Int8x16) Store(s []int8)

// LoadInt16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadInt16x8(s []int16) (z Int16x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Int16x8) Store(s []int16)

// LoadInt32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadInt32x4(s []int32) (z Int32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Int32x4) Store(s []int32)

// LoadInt64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadInt64x2(s []int64) (z Int64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Int64x2) Store(s []int64)

// LoadUint8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadUint8x16(s []uint8) (z Uint8x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Uint8x16) Store(s []uint8)

// LoadUint16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadUint16x8(s []uint16) (z Uint16x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Uint16x8) Store(s []uint16)

// LoadUint32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadUint32x4(s []uint32) (z Uint32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Uint32x4) Store(s []uint32)

// LoadUint64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadUint64x2(s []uint64) (z Uint64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Uint64x2) Store(s []uint64)

// LoadFloat32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadFloat32x4(s []float32) (z Float32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Float32x4) Store(s []float32)

// LoadFloat64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadFloat64x2(s []float64) (z Float64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Float64x2) Store(s []float64)
