// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd

package archsimd

// LoadInt8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadInt8x16(s []int8) (z Int8x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Int8x16) Store(s []int8)

// LoadInt16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadInt16x8(s []int16) (z Int16x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Int16x8) Store(s []int16)

// LoadInt32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadInt32x4(s []int32) (z Int32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Int32x4) Store(s []int32)

// LoadInt64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadInt64x2(s []int64) (z Int64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Int64x2) Store(s []int64)

// LoadUint8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadUint8x16(s []uint8) (z Uint8x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Uint8x16) Store(s []uint8)

// LoadUint16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadUint16x8(s []uint16) (z Uint16x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Uint16x8) Store(s []uint16)

// LoadUint32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadUint32x4(s []uint32) (z Uint32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Uint32x4) Store(s []uint32)

// LoadUint64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadUint64x2(s []uint64) (z Uint64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Uint64x2) Store(s []uint64)

// LoadFloat32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadFloat32x4(s []float32) (z Float32x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Float32x4) Store(s []float32)

// LoadFloat64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadFloat64x2(s []float64) (z Float64x2)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Float64x2) Store(s []float64)

// LoadInt8x32 loads a slice into a vector. If len(s) < 32, it panics.
func LoadInt8x32(s []int8) (z Int8x32)

// Store stores the elements of x into a slice. If len(s) < 32, it panics.
func (x Int8x32) Store(s []int8)

// LoadInt16x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadInt16x16(s []int16) (z Int16x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Int16x16) Store(s []int16)

// LoadInt32x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadInt32x8(s []int32) (z Int32x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Int32x8) Store(s []int32)

// LoadInt64x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadInt64x4(s []int64) (z Int64x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Int64x4) Store(s []int64)

// LoadUint8x32 loads a slice into a vector. If len(s) < 32, it panics.
func LoadUint8x32(s []uint8) (z Uint8x32)

// Store stores the elements of x into a slice. If len(s) < 32, it panics.
func (x Uint8x32) Store(s []uint8)

// LoadUint16x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadUint16x16(s []uint16) (z Uint16x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Uint16x16) Store(s []uint16)

// LoadUint32x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadUint32x8(s []uint32) (z Uint32x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Uint32x8) Store(s []uint32)

// LoadUint64x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadUint64x4(s []uint64) (z Uint64x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Uint64x4) Store(s []uint64)

// LoadFloat32x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadFloat32x8(s []float32) (z Float32x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Float32x8) Store(s []float32)

// LoadFloat64x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadFloat64x4(s []float64) (z Float64x4)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Float64x4) Store(s []float64)

// LoadInt8x64 loads a slice into a vector. If len(s) < 64, it panics.
func LoadInt8x64(s []int8) (z Int8x64)

// Store stores the elements of x into a slice. If len(s) < 64, it panics.
func (x Int8x64) Store(s []int8)

// LoadInt16x32 loads a slice into a vector. If len(s) < 32, it panics.
func LoadInt16x32(s []int16) (z Int16x32)

// Store stores the elements of x into a slice. If len(s) < 32, it panics.
func (x Int16x32) Store(s []int16)

// LoadInt32x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadInt32x16(s []int32) (z Int32x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Int32x16) Store(s []int32)

// LoadInt64x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadInt64x8(s []int64) (z Int64x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Int64x8) Store(s []int64)

// LoadUint8x64 loads a slice into a vector. If len(s) < 64, it panics.
func LoadUint8x64(s []uint8) (z Uint8x64)

// Store stores the elements of x into a slice. If len(s) < 64, it panics.
func (x Uint8x64) Store(s []uint8)

// LoadUint16x32 loads a slice into a vector. If len(s) < 32, it panics.
func LoadUint16x32(s []uint16) (z Uint16x32)

// Store stores the elements of x into a slice. If len(s) < 32, it panics.
func (x Uint16x32) Store(s []uint16)

// LoadUint32x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadUint32x16(s []uint32) (z Uint32x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Uint32x16) Store(s []uint32)

// LoadUint64x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadUint64x8(s []uint64) (z Uint64x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Uint64x8) Store(s []uint64)

// LoadFloat32x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadFloat32x16(s []float32) (z Float32x16)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Float32x16) Store(s []float32)

// LoadFloat64x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadFloat64x8(s []float64) (z Float64x8)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Float64x8) Store(s []float64)

// LoadInt8x64Part loads n=min(len(s), 64) elements from slice s as a
// vector and returns the vector and n. If len(s) < 64, the
// remaining vector elements will be zero.
func LoadInt8x64Part(s []int8) (z Int8x64, n int)

// StorePart stores n=min(len(s), 64) elements of x into s and returns n.
func (x Int8x64) StorePart(s []int8) (n int)

// LoadInt16x32Part loads n=min(len(s), 32) elements from slice s as a
// vector and returns the vector and n. If len(s) < 32, the
// remaining vector elements will be zero.
func LoadInt16x32Part(s []int16) (z Int16x32, n int)

// StorePart stores n=min(len(s), 32) elements of x into s and returns n.
func (x Int16x32) StorePart(s []int16) (n int)

// LoadInt32x16Part loads n=min(len(s), 16) elements from slice s as a
// vector and returns the vector and n. If len(s) < 16, the
// remaining vector elements will be zero.
func LoadInt32x16Part(s []int32) (z Int32x16, n int)

// StorePart stores n=min(len(s), 16) elements of x into s and returns n.
func (x Int32x16) StorePart(s []int32) (n int)

// LoadInt64x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadInt64x8Part(s []int64) (z Int64x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Int64x8) StorePart(s []int64) (n int)

// LoadUint8x64Part loads n=min(len(s), 64) elements from slice s as a
// vector and returns the vector and n. If len(s) < 64, the
// remaining vector elements will be zero.
func LoadUint8x64Part(s []uint8) (z Uint8x64, n int)

// StorePart stores n=min(len(s), 64) elements of x into s and returns n.
func (x Uint8x64) StorePart(s []uint8) (n int)

// LoadUint16x32Part loads n=min(len(s), 32) elements from slice s as a
// vector and returns the vector and n. If len(s) < 32, the
// remaining vector elements will be zero.
func LoadUint16x32Part(s []uint16) (z Uint16x32, n int)

// StorePart stores n=min(len(s), 32) elements of x into s and returns n.
func (x Uint16x32) StorePart(s []uint16) (n int)

// LoadUint32x16Part loads n=min(len(s), 16) elements from slice s as a
// vector and returns the vector and n. If len(s) < 16, the
// remaining vector elements will be zero.
func LoadUint32x16Part(s []uint32) (z Uint32x16, n int)

// StorePart stores n=min(len(s), 16) elements of x into s and returns n.
func (x Uint32x16) StorePart(s []uint32) (n int)

// LoadUint64x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadUint64x8Part(s []uint64) (z Uint64x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Uint64x8) StorePart(s []uint64) (n int)

// LoadFloat32x16Part loads n=min(len(s), 16) elements from slice s as a
// vector and returns the vector and n. If len(s) < 16, the
// remaining vector elements will be zero.
func LoadFloat32x16Part(s []float32) (z Float32x16, n int)

// StorePart stores n=min(len(s), 16) elements of x into s and returns n.
func (x Float32x16) StorePart(s []float32) (n int)

// LoadFloat64x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadFloat64x8Part(s []float64) (z Float64x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Float64x8) StorePart(s []float64) (n int)

// LoadInt32x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadInt32x4Part(s []int32) (z Int32x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Int32x4) StorePart(s []int32) (n int)

// LoadInt64x2Part loads n=min(len(s), 2) elements from slice s as a
// vector and returns the vector and n. If len(s) < 2, the
// remaining vector elements will be zero.
func LoadInt64x2Part(s []int64) (z Int64x2, n int)

// StorePart stores n=min(len(s), 2) elements of x into s and returns n.
func (x Int64x2) StorePart(s []int64) (n int)

// LoadUint32x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadUint32x4Part(s []uint32) (z Uint32x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Uint32x4) StorePart(s []uint32) (n int)

// LoadUint64x2Part loads n=min(len(s), 2) elements from slice s as a
// vector and returns the vector and n. If len(s) < 2, the
// remaining vector elements will be zero.
func LoadUint64x2Part(s []uint64) (z Uint64x2, n int)

// StorePart stores n=min(len(s), 2) elements of x into s and returns n.
func (x Uint64x2) StorePart(s []uint64) (n int)

// LoadFloat32x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadFloat32x4Part(s []float32) (z Float32x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Float32x4) StorePart(s []float32) (n int)

// LoadFloat64x2Part loads n=min(len(s), 2) elements from slice s as a
// vector and returns the vector and n. If len(s) < 2, the
// remaining vector elements will be zero.
func LoadFloat64x2Part(s []float64) (z Float64x2, n int)

// StorePart stores n=min(len(s), 2) elements of x into s and returns n.
func (x Float64x2) StorePart(s []float64) (n int)

// LoadInt32x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadInt32x8Part(s []int32) (z Int32x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Int32x8) StorePart(s []int32) (n int)

// LoadInt64x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadInt64x4Part(s []int64) (z Int64x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Int64x4) StorePart(s []int64) (n int)

// LoadUint32x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadUint32x8Part(s []uint32) (z Uint32x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Uint32x8) StorePart(s []uint32) (n int)

// LoadUint64x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadUint64x4Part(s []uint64) (z Uint64x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Uint64x4) StorePart(s []uint64) (n int)

// LoadFloat32x8Part loads n=min(len(s), 8) elements from slice s as a
// vector and returns the vector and n. If len(s) < 8, the
// remaining vector elements will be zero.
func LoadFloat32x8Part(s []float32) (z Float32x8, n int)

// StorePart stores n=min(len(s), 8) elements of x into s and returns n.
func (x Float32x8) StorePart(s []float32) (n int)

// LoadFloat64x4Part loads n=min(len(s), 4) elements from slice s as a
// vector and returns the vector and n. If len(s) < 4, the
// remaining vector elements will be zero.
func LoadFloat64x4Part(s []float64) (z Float64x4, n int)

// StorePart stores n=min(len(s), 4) elements of x into s and returns n.
func (x Float64x4) StorePart(s []float64) (n int)

// LoadUint8x32Part loads n=min(len(s), 32) elements from slice s as a
// vector and returns the vector and n. If len(s) < 32, the
// remaining vector elements will be zero.
func LoadUint8x32Part(s []uint8) (z Uint8x32, n int)

// StorePart stores n=min(len(s), 32) elements of x into s and returns n.
func (x Uint8x32) StorePart(s []uint8) (n int)

// LoadUint16x16Part loads n=min(len(s), 16) elements from slice s as a
// vector and returns the vector and n. If len(s) < 16, the
// remaining vector elements will be zero.
func LoadUint16x16Part(s []uint16) (z Uint16x16, n int)

// StorePart stores n=min(len(s), 16) elements of x into s and returns n.
func (x Uint16x16) StorePart(s []uint16) (n int)
