// Code generated by 'simdgen -o godefs -goroot $GOROOT -arch sve -arm64Path $ARM64_ISA_PATH go_sve.yaml types.yaml categories.yaml'; DO NOT EDIT.

//go:build goexperiment.simd && arm64

package archsimd

// Float32s is a scalable SIMD vector of float32s.
type Float32s struct {
	float32x8 v256
	vals      [8]float32
}

// Len returns the number of elements in a Float32s.
func (x Float32s) Len() int

// LoadFloat32s loads a Float32s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadFloat32s(s []float32) Float32s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Float32s) Store(s []float32)

// LoadFloat32sPart loads a Float32s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadFloat32sPart(s []float32) (Float32s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Float32s) StorePart(s []float32) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Float32s) IfElse(mask Mask32s, y Float32s) Float32s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Float32s) Masked(mask Mask32s) Float32s

// BroadcastFloat32s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastFloat32s(x float32) Float32s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Float32s) String() string

// Float64s is a scalable SIMD vector of float64s.
type Float64s struct {
	float64x4 v256
	vals      [4]float64
}

// Len returns the number of elements in a Float64s.
func (x Float64s) Len() int

// LoadFloat64s loads a Float64s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadFloat64s(s []float64) Float64s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Float64s) Store(s []float64)

// LoadFloat64sPart loads a Float64s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadFloat64sPart(s []float64) (Float64s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Float64s) StorePart(s []float64) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Float64s) IfElse(mask Mask64s, y Float64s) Float64s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Float64s) Masked(mask Mask64s) Float64s

// BroadcastFloat64s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastFloat64s(x float64) Float64s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Float64s) String() string

// Int8s is a scalable SIMD vector of int8s.
type Int8s struct {
	int8x32 v256
	vals    [32]int8
}

// Len returns the number of elements in an Int8s.
func (x Int8s) Len() int

// LoadInt8s loads an Int8s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadInt8s(s []int8) Int8s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Int8s) Store(s []int8)

// LoadInt8sPart loads an Int8s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadInt8sPart(s []int8) (Int8s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Int8s) StorePart(s []int8) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Int8s) IfElse(mask Mask8s, y Int8s) Int8s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Int8s) Masked(mask Mask8s) Int8s

// BroadcastInt8s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastInt8s(x int8) Int8s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Int8s) String() string

// Int16s is a scalable SIMD vector of int16s.
type Int16s struct {
	int16x16 v256
	vals     [16]int16
}

// Len returns the number of elements in an Int16s.
func (x Int16s) Len() int

// LoadInt16s loads an Int16s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadInt16s(s []int16) Int16s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Int16s) Store(s []int16)

// LoadInt16sPart loads an Int16s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadInt16sPart(s []int16) (Int16s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Int16s) StorePart(s []int16) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Int16s) IfElse(mask Mask16s, y Int16s) Int16s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Int16s) Masked(mask Mask16s) Int16s

// BroadcastInt16s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastInt16s(x int16) Int16s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Int16s) String() string

// Int32s is a scalable SIMD vector of int32s.
type Int32s struct {
	int32x8 v256
	vals    [8]int32
}

// Len returns the number of elements in an Int32s.
func (x Int32s) Len() int

// LoadInt32s loads an Int32s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadInt32s(s []int32) Int32s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Int32s) Store(s []int32)

// LoadInt32sPart loads an Int32s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadInt32sPart(s []int32) (Int32s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Int32s) StorePart(s []int32) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Int32s) IfElse(mask Mask32s, y Int32s) Int32s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Int32s) Masked(mask Mask32s) Int32s

// BroadcastInt32s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastInt32s(x int32) Int32s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Int32s) String() string

// Int64s is a scalable SIMD vector of int64s.
type Int64s struct {
	int64x4 v256
	vals    [4]int64
}

// Len returns the number of elements in an Int64s.
func (x Int64s) Len() int

// LoadInt64s loads an Int64s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadInt64s(s []int64) Int64s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Int64s) Store(s []int64)

// LoadInt64sPart loads an Int64s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadInt64sPart(s []int64) (Int64s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Int64s) StorePart(s []int64) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Int64s) IfElse(mask Mask64s, y Int64s) Int64s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Int64s) Masked(mask Mask64s) Int64s

// BroadcastInt64s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastInt64s(x int64) Int64s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Int64s) String() string

// Uint8s is a scalable SIMD vector of uint8s.
type Uint8s struct {
	uint8x32 v256
	vals     [32]uint8
}

// Len returns the number of elements in a Uint8s.
func (x Uint8s) Len() int

// LoadUint8s loads a Uint8s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadUint8s(s []uint8) Uint8s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Uint8s) Store(s []uint8)

// LoadUint8sPart loads a Uint8s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadUint8sPart(s []uint8) (Uint8s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Uint8s) StorePart(s []uint8) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Uint8s) IfElse(mask Mask8s, y Uint8s) Uint8s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Uint8s) Masked(mask Mask8s) Uint8s

// BroadcastUint8s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastUint8s(x uint8) Uint8s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Uint8s) String() string

// Uint16s is a scalable SIMD vector of uint16s.
type Uint16s struct {
	uint16x16 v256
	vals      [16]uint16
}

// Len returns the number of elements in a Uint16s.
func (x Uint16s) Len() int

// LoadUint16s loads a Uint16s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadUint16s(s []uint16) Uint16s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Uint16s) Store(s []uint16)

// LoadUint16sPart loads a Uint16s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadUint16sPart(s []uint16) (Uint16s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Uint16s) StorePart(s []uint16) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Uint16s) IfElse(mask Mask16s, y Uint16s) Uint16s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Uint16s) Masked(mask Mask16s) Uint16s

// BroadcastUint16s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastUint16s(x uint16) Uint16s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Uint16s) String() string

// Uint32s is a scalable SIMD vector of uint32s.
type Uint32s struct {
	uint32x8 v256
	vals     [8]uint32
}

// Len returns the number of elements in a Uint32s.
func (x Uint32s) Len() int

// LoadUint32s loads a Uint32s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadUint32s(s []uint32) Uint32s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Uint32s) Store(s []uint32)

// LoadUint32sPart loads a Uint32s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadUint32sPart(s []uint32) (Uint32s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Uint32s) StorePart(s []uint32) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Uint32s) IfElse(mask Mask32s, y Uint32s) Uint32s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Uint32s) Masked(mask Mask32s) Uint32s

// BroadcastUint32s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastUint32s(x uint32) Uint32s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Uint32s) String() string

// Uint64s is a scalable SIMD vector of uint64s.
type Uint64s struct {
	uint64x4 v256
	vals     [4]uint64
}

// Len returns the number of elements in a Uint64s.
func (x Uint64s) Len() int

// LoadUint64s loads a Uint64s from the first Len() elements of s.
// It panics if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZLDR).
func LoadUint64s(s []uint64) Uint64s

// Store stores x's Len() elements into the first Len() elements of s. It panics
// if len(s) < Len().
//
// Asm: Emulated (a length check that can panic, then ZSTR).
func (x Uint64s) Store(s []uint64)

// LoadUint64sPart loads a Uint64s from s, reading n = min(len(s),
// Len()) elements and returning the vector and n; the remaining elements are
// zero.
//
// Asm: Emulated (predicate construction + LD1B).
func LoadUint64sPart(s []uint64) (Uint64s, int)

// StorePart stores the low n = min(len(s), Len()) elements of x into s and
// returns n.
//
// Asm: Emulated (predicate construction + ST1B).
func (x Uint64s) StorePart(s []uint64) int

// IfElse returns the elements of x where the corresponding element of mask is
// true, and the elements of y where it is false.
//
// Asm: ZSEL
func (x Uint64s) IfElse(mask Mask64s, y Uint64s) Uint64s

// Masked returns the elements of x where the corresponding element of mask is
// true, and zero where it is false.
//
// Asm: Emulated
func (x Uint64s) Masked(mask Mask64s) Uint64s

// BroadcastUint64s returns a vector with the input x assigned to all
// elements of the output.
//
// Asm: ZDUP, CPU Feature: SVE
func BroadcastUint64s(x uint64) Uint64s

// String returns a string representation of SIMD vector x. Only the x.Len()
// elements that exist at the runtime vector length are shown.
func (x Uint64s) String() string

// Mask8s is a scalable mask for a SIMD vector of 8-bit elements.
//
// An SVE predicate holds one bit per byte of the vector it governs, so a
// Mask8s carries one bit for each byte of the runtime vector length, and
// lane i is governed by bit i.
//
// In memory a Mask8s is a uint64 holding those bits, bit 0 first; the bits
// beyond the runtime vector length are zero. So the bits of m can be read with
// *(*uint64)(unsafe.Pointer(&m)).
type Mask8s struct {
	mask8s psve
	vals   uint64
}

// Mask8sAllTrue returns a mask with every lane true.
//
// Asm: PWHILELT, CPU Feature: SVE
func Mask8sAllTrue() Mask8s

// First returns a mask with only the first active lane of m active, or no
// lanes active if m has none.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask8s) First() Mask8s

// Next returns a mask with only the lane after the last active lane of m
// active. If m has no active lanes, lane 0 is active; if its last active lane
// is the last lane, no lanes are active.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask8s) Next() Mask8s

// All reports whether every lane of m is active.
//
// Asm: BICS (predicate), CPU Feature: SVE
func (m Mask8s) All() bool

// None reports whether no lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask8s) None() bool

// Any reports whether some lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask8s) Any() bool

// String returns a string representation of SIMD mask m: 1 for an active lane,
// 0 for an inactive one. Only the vl() lanes that exist at the runtime
// vector length are shown.
func (m Mask8s) String() string

// Mask16s is a scalable mask for a SIMD vector of 16-bit elements.
//
// An SVE predicate holds one bit per byte of the vector it governs, so a
// Mask16s carries one bit for each byte of the runtime vector length, and
// lane i is governed by bit 2*i. The bits in between are ignored.
//
// In memory a Mask16s is a uint64 holding those bits, bit 0 first; the bits
// beyond the runtime vector length are zero. So the bits of m can be read with
// *(*uint64)(unsafe.Pointer(&m)).
type Mask16s struct {
	mask16s psve
	vals    uint64
}

// Mask16sAllTrue returns a mask with every lane true.
//
// Asm: PWHILELT, CPU Feature: SVE
func Mask16sAllTrue() Mask16s

// First returns a mask with only the first active lane of m active, or no
// lanes active if m has none.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask16s) First() Mask16s

// Next returns a mask with only the lane after the last active lane of m
// active. If m has no active lanes, lane 0 is active; if its last active lane
// is the last lane, no lanes are active.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask16s) Next() Mask16s

// All reports whether every lane of m is active.
//
// Asm: BICS (predicate), CPU Feature: SVE
func (m Mask16s) All() bool

// None reports whether no lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask16s) None() bool

// Any reports whether some lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask16s) Any() bool

// String returns a string representation of SIMD mask m: 1 for an active lane,
// 0 for an inactive one. Only the vl() / 2 lanes that exist at the runtime
// vector length are shown.
func (m Mask16s) String() string

// Mask32s is a scalable mask for a SIMD vector of 32-bit elements.
//
// An SVE predicate holds one bit per byte of the vector it governs, so a
// Mask32s carries one bit for each byte of the runtime vector length, and
// lane i is governed by bit 4*i. The bits in between are ignored.
//
// In memory a Mask32s is a uint64 holding those bits, bit 0 first; the bits
// beyond the runtime vector length are zero. So the bits of m can be read with
// *(*uint64)(unsafe.Pointer(&m)).
type Mask32s struct {
	mask32s psve
	vals    uint64
}

// Mask32sAllTrue returns a mask with every lane true.
//
// Asm: PWHILELT, CPU Feature: SVE
func Mask32sAllTrue() Mask32s

// First returns a mask with only the first active lane of m active, or no
// lanes active if m has none.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask32s) First() Mask32s

// Next returns a mask with only the lane after the last active lane of m
// active. If m has no active lanes, lane 0 is active; if its last active lane
// is the last lane, no lanes are active.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask32s) Next() Mask32s

// All reports whether every lane of m is active.
//
// Asm: BICS (predicate), CPU Feature: SVE
func (m Mask32s) All() bool

// None reports whether no lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask32s) None() bool

// Any reports whether some lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask32s) Any() bool

// String returns a string representation of SIMD mask m: 1 for an active lane,
// 0 for an inactive one. Only the vl() / 4 lanes that exist at the runtime
// vector length are shown.
func (m Mask32s) String() string

// Mask64s is a scalable mask for a SIMD vector of 64-bit elements.
//
// An SVE predicate holds one bit per byte of the vector it governs, so a
// Mask64s carries one bit for each byte of the runtime vector length, and
// lane i is governed by bit 8*i. The bits in between are ignored.
//
// In memory a Mask64s is a uint64 holding those bits, bit 0 first; the bits
// beyond the runtime vector length are zero. So the bits of m can be read with
// *(*uint64)(unsafe.Pointer(&m)).
type Mask64s struct {
	mask64s psve
	vals    uint64
}

// Mask64sAllTrue returns a mask with every lane true.
//
// Asm: PWHILELT, CPU Feature: SVE
func Mask64sAllTrue() Mask64s

// First returns a mask with only the first active lane of m active, or no
// lanes active if m has none.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask64s) First() Mask64s

// Next returns a mask with only the lane after the last active lane of m
// active. If m has no active lanes, lane 0 is active; if its last active lane
// is the last lane, no lanes are active.
//
// Asm: PNEXT, CPU Feature: SVE
func (m Mask64s) Next() Mask64s

// All reports whether every lane of m is active.
//
// Asm: BICS (predicate), CPU Feature: SVE
func (m Mask64s) All() bool

// None reports whether no lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask64s) None() bool

// Any reports whether some lane of m is active.
//
// Asm: PTEST, CPU Feature: SVE
func (m Mask64s) Any() bool

// String returns a string representation of SIMD mask m: 1 for an active lane,
// 0 for an inactive one. Only the vl() / 8 lanes that exist at the runtime
// vector length are shown.
func (m Mask64s) String() string
