// Code generated by 'wasmgen'; DO NOT EDIT.

//go:build goexperiment.simd && wasm

package archsimd

// Int8x16 is a 128-bit SIMD vector of 16 int8s.
type Int8x16 struct {
	int8x16 v128
	vals    [16]int8
}

// Len returns the number of elements in an Int8x16.
func (x Int8x16) Len() int

// LoadInt8x16Array loads an array into a vector.
//
//go:noescape
func LoadInt8x16Array(x *[16]int8) (z Int8x16)

// LoadInt8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadInt8x16(s []int8) (z Int8x16)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Int8x16) StoreArray(y *[16]int8)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Int8x16) Store(s []int8)

// BroadcastInt8x16 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastInt8x16(x int8) (z Int8x16)

// Int16x8 is a 128-bit SIMD vector of 8 int16s.
type Int16x8 struct {
	int16x8 v128
	vals    [8]int16
}

// Len returns the number of elements in an Int16x8.
func (x Int16x8) Len() int

// LoadInt16x8Array loads an array into a vector.
//
//go:noescape
func LoadInt16x8Array(x *[8]int16) (z Int16x8)

// LoadInt16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadInt16x8(s []int16) (z Int16x8)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Int16x8) StoreArray(y *[8]int16)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Int16x8) Store(s []int16)

// BroadcastInt16x8 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastInt16x8(x int16) (z Int16x8)

// Int32x4 is a 128-bit SIMD vector of 4 int32s.
type Int32x4 struct {
	int32x4 v128
	vals    [4]int32
}

// Len returns the number of elements in an Int32x4.
func (x Int32x4) Len() int

// LoadInt32x4Array loads an array into a vector.
//
//go:noescape
func LoadInt32x4Array(x *[4]int32) (z Int32x4)

// LoadInt32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadInt32x4(s []int32) (z Int32x4)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Int32x4) StoreArray(y *[4]int32)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Int32x4) Store(s []int32)

// BroadcastInt32x4 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastInt32x4(x int32) (z Int32x4)

// Int64x2 is a 128-bit SIMD vector of 2 int64s.
type Int64x2 struct {
	int64x2 v128
	vals    [2]int64
}

// Len returns the number of elements in an Int64x2.
func (x Int64x2) Len() int

// LoadInt64x2Array loads an array into a vector.
//
//go:noescape
func LoadInt64x2Array(x *[2]int64) (z Int64x2)

// LoadInt64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadInt64x2(s []int64) (z Int64x2)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Int64x2) StoreArray(y *[2]int64)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Int64x2) Store(s []int64)

// BroadcastInt64x2 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastInt64x2(x int64) (z Int64x2)

// Uint8x16 is a 128-bit SIMD vector of 16 uint8s.
type Uint8x16 struct {
	uint8x16 v128
	vals     [16]uint8
}

// Len returns the number of elements in a Uint8x16.
func (x Uint8x16) Len() int

// LoadUint8x16Array loads an array into a vector.
//
//go:noescape
func LoadUint8x16Array(x *[16]uint8) (z Uint8x16)

// LoadUint8x16 loads a slice into a vector. If len(s) < 16, it panics.
func LoadUint8x16(s []uint8) (z Uint8x16)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Uint8x16) StoreArray(y *[16]uint8)

// Store stores the elements of x into a slice. If len(s) < 16, it panics.
func (x Uint8x16) Store(s []uint8)

// BroadcastUint8x16 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastUint8x16(x uint8) (z Uint8x16)

// Uint16x8 is a 128-bit SIMD vector of 8 uint16s.
type Uint16x8 struct {
	uint16x8 v128
	vals     [8]uint16
}

// Len returns the number of elements in a Uint16x8.
func (x Uint16x8) Len() int

// LoadUint16x8Array loads an array into a vector.
//
//go:noescape
func LoadUint16x8Array(x *[8]uint16) (z Uint16x8)

// LoadUint16x8 loads a slice into a vector. If len(s) < 8, it panics.
func LoadUint16x8(s []uint16) (z Uint16x8)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Uint16x8) StoreArray(y *[8]uint16)

// Store stores the elements of x into a slice. If len(s) < 8, it panics.
func (x Uint16x8) Store(s []uint16)

// BroadcastUint16x8 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastUint16x8(x uint16) (z Uint16x8)

// Uint32x4 is a 128-bit SIMD vector of 4 uint32s.
type Uint32x4 struct {
	uint32x4 v128
	vals     [4]uint32
}

// Len returns the number of elements in a Uint32x4.
func (x Uint32x4) Len() int

// LoadUint32x4Array loads an array into a vector.
//
//go:noescape
func LoadUint32x4Array(x *[4]uint32) (z Uint32x4)

// LoadUint32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadUint32x4(s []uint32) (z Uint32x4)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Uint32x4) StoreArray(y *[4]uint32)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Uint32x4) Store(s []uint32)

// BroadcastUint32x4 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastUint32x4(x uint32) (z Uint32x4)

// Uint64x2 is a 128-bit SIMD vector of 2 uint64s.
type Uint64x2 struct {
	uint64x2 v128
	vals     [2]uint64
}

// Len returns the number of elements in a Uint64x2.
func (x Uint64x2) Len() int

// LoadUint64x2Array loads an array into a vector.
//
//go:noescape
func LoadUint64x2Array(x *[2]uint64) (z Uint64x2)

// LoadUint64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadUint64x2(s []uint64) (z Uint64x2)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Uint64x2) StoreArray(y *[2]uint64)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Uint64x2) Store(s []uint64)

// BroadcastUint64x2 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastUint64x2(x uint64) (z Uint64x2)

// Float32x4 is a 128-bit SIMD vector of 4 float32s.
type Float32x4 struct {
	float32x4 v128
	vals      [4]float32
}

// Len returns the number of elements in a Float32x4.
func (x Float32x4) Len() int

// LoadFloat32x4Array loads an array into a vector.
//
//go:noescape
func LoadFloat32x4Array(x *[4]float32) (z Float32x4)

// LoadFloat32x4 loads a slice into a vector. If len(s) < 4, it panics.
func LoadFloat32x4(s []float32) (z Float32x4)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Float32x4) StoreArray(y *[4]float32)

// Store stores the elements of x into a slice. If len(s) < 4, it panics.
func (x Float32x4) Store(s []float32)

// BroadcastFloat32x4 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastFloat32x4(x float32) (z Float32x4)

// Float64x2 is a 128-bit SIMD vector of 2 float64s.
type Float64x2 struct {
	float64x2 v128
	vals      [2]float64
}

// Len returns the number of elements in a Float64x2.
func (x Float64x2) Len() int

// LoadFloat64x2Array loads an array into a vector.
//
//go:noescape
func LoadFloat64x2Array(x *[2]float64) (z Float64x2)

// LoadFloat64x2 loads a slice into a vector. If len(s) < 2, it panics.
func LoadFloat64x2(s []float64) (z Float64x2)

// StoreArray stores the elements of x to an array.
//
//go:noescape
func (x Float64x2) StoreArray(y *[2]float64)

// Store stores the elements of x into a slice. If len(s) < 2, it panics.
func (x Float64x2) Store(s []float64)

// BroadcastFloat64x2 returns a vector with the input x assigned to all elements of the
// result.
func BroadcastFloat64x2(x float64) (z Float64x2)

// Mask8x16 is a 128-bit SIMD mask of 16 int8s.
type Mask8x16 struct {
	int8x16 v128
	vals    [16]int8
}

// Mask16x8 is a 128-bit SIMD mask of 8 int16s.
type Mask16x8 struct {
	int16x8 v128
	vals    [8]int16
}

// Mask32x4 is a 128-bit SIMD mask of 4 int32s.
type Mask32x4 struct {
	int32x4 v128
	vals    [4]int32
}

// Mask64x2 is a 128-bit SIMD mask of 2 int64s.
type Mask64x2 struct {
	int64x2 v128
	vals    [2]int64
}
