// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by go run makeisprint.go -output isprint.go; DO NOT EDIT.

package strconv

// isGraphic lists the graphic runes not matched by IsPrint.
