// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// DO NOT EDIT.  GENERATED BY
//     go run makeisprint.go >x && mv x isprint.go

package strconv
