// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by: go run pow10gen.go. DO NOT EDIT.
//
//go:generate go run pow10gen.go

package strconv
