// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build goexperiment.simd

package test_helpers

import (
	"github.com/shogo82148/std/testing"
)

func ReduceSum[S number](s []S) S

func Neg[S number](x S) S

func Abs[S number](x S) S

func Add[S number](x, y S) S

func Sub[S number](x, y S) S

func Mul[S number](x, y S) S

func Div[S float](x, y S) S

func And[S integer](x, y S) S

func Or[S integer](x, y S) S

func Xor[S integer](x, y S) S

func AndNot[S integer](x, y S) S

func Max[S number](x, y S) S

func Min[S number](x, y S) S

func ShiftLeft[S integer](x S, s uint64) S

func ShiftRight[S integer](x S, s uint64) S

func Equal[S number](x, y S) bool

func NotEqual[S number](x, y S) bool

func Less[S number](x, y S) bool

func LessEqual[S number](x, y S) bool

func Greater[S number](x, y S) bool

func GreaterEqual[S number](x, y S) bool

func RotateLeft[S integer](x S, dist uint64) S

func RotateRight[S integer](x S, dist uint64) S

type Vec[E number] interface {
	Store(s []E)
	Len() int
}

type Mask interface {
	String() string
}

// TestV2S tests the simd Vector-To-Scalar method f against the expected behavior generated by want
func TestV2S[S number, V Vec[S]](t *testing.T, slice []S, load func([]S) V, f func(_ V) S, want func([]S) S)

// TestV2V tests the simd Vector-To-Vector method f against the expected behavior generated by want
func TestV2V[S number, V Vec[S]](t *testing.T, slice []S, load func([]S) V, f func(_ V) V, want func([]S) []S)

// TestV2Ve tests the simd unary Vector-To-Vector method f against the expected behavior generated by per-Element function want
func TestV2Ve[S number, V Vec[S]](t *testing.T, slice []S, load func([]S) V, f func(_ V) V, want func(S) S)

// TestV2Ve tests the simd binary (Vector,Rotation)-To-Vector method f against the expected behavior generated by per-Element function want
func TestVR2Ve[S number, V Vec[S]](t *testing.T, slice []S, shifts []uint64, load func([]S) V, f func(V, uint64) V, want func(S, uint64) S)

// TestVV2V tests the simd binary (vector,vector)-to-vector method f against the expected behavior generated by want
func TestVV2V[S number, V Vec[S]](t *testing.T, slice []S, load func([]S) V, f func(_, _ V) V, want func(_, _ []S) []S)

// TestVV2Ve tests the simd binary (Vector,Vector)-To-Vector method f against the expected behavior generated by per-Element function want
func TestVV2Ve[S number, V Vec[S]](t *testing.T, slice []S, load func([]S) V, f func(_, _ V) V, want func(_, _ S) S)

// TestVV2Me tests the simd comparison method f against the expected behavior generated by bool want
func TestVV2Me[S number, V Vec[S], M Mask](t *testing.T, slice []S, load func([]S) V, f func(_, _ V) M, want func(_, _ S) bool)
