// Code generated by 'tmplgen'; DO NOT EDIT.

//go:build goexperiment.simd && (amd64 || wasm)

// This file contains functions testing unary simd methods.
// Each function in this file is specialized for a
// particular simd type <BaseType><Width>x<Count>.

package simd_test
