// Copyright 2010 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ioutil

import (
	"github.com/shogo82148/std/os"
)

<<<<<<< HEAD
// TempFileは、ディレクトリdirに新しい一時ファイルを作成し、
// ファイルを読み書きするために開き、結果の*os.Fileを返します。
// ファイル名は、patternを取り、ランダムな文字列を末尾に追加して生成されます。
// patternに"*"が含まれている場合、ランダムな文字列が最後の"*"に置き換えられます。
// dirが空の文字列の場合、TempFileは一時ファイルのデフォルトディレクトリを使用します（os.TempDirを参照）。
// 同時にTempFileを呼び出す複数のプログラムは、同じファイルを選択しません。
// 呼び出し元は、f.Name()を使用してファイルのパス名を見つけることができます。
// ファイルが不要になったら、呼び出し元の責任でファイルを削除する必要があります。
=======
// TempFile creates a new temporary file in the directory dir,
// opens the file for reading and writing, and returns the resulting *[os.File].
// The filename is generated by taking pattern and adding a random
// string to the end. If pattern includes a "*", the random string
// replaces the last "*".
// If dir is the empty string, TempFile uses the default directory
// for temporary files (see [os.TempDir]).
// Multiple programs calling TempFile simultaneously
// will not choose the same file. The caller can use f.Name()
// to find the pathname of the file. It is the caller's responsibility
// to remove the file when no longer needed.
>>>>>>> upstream/master
//
// Deprecated: Go 1.17以降、この関数は単に[os.CreateTemp]を呼び出すだけです。
func TempFile(dir, pattern string) (f *os.File, err error)

<<<<<<< HEAD
// TempDirは、ディレクトリdirに新しい一時ディレクトリを作成し、
// ディレクトリ名を生成するためにpatternを取り、ランダムな文字列を末尾に追加します。
// patternに"*"が含まれている場合、ランダムな文字列が最後の"*"に置き換えられます。
// TempDirは、新しいディレクトリの名前を返します。
// dirが空の文字列の場合、TempDirは一時ファイルのデフォルトディレクトリを使用します（os.TempDirを参照）。
// 同時にTempDirを呼び出す複数のプログラムは、同じディレクトリを選択しません。
// 呼び出し元は、ディレクトリが不要になったら削除する責任があります。
=======
// TempDir creates a new temporary directory in the directory dir.
// The directory name is generated by taking pattern and applying a
// random string to the end. If pattern includes a "*", the random string
// replaces the last "*". TempDir returns the name of the new directory.
// If dir is the empty string, TempDir uses the
// default directory for temporary files (see [os.TempDir]).
// Multiple programs calling TempDir simultaneously
// will not choose the same directory. It is the caller's responsibility
// to remove the directory when no longer needed.
>>>>>>> upstream/master
//
// Deprecated: Go 1.17以降、この関数は単に[os.MkdirTemp]を呼び出すだけです。
func TempDir(dir, pattern string) (name string, err error)
