// mksyscall.pl -nacl -tags nacl,amd64p32 syscall_nacl.go syscall_nacl_amd64p32.go
// Code generated by the command above; DO NOT EDIT.

//go:build nacl && amd64p32
// +build nacl,amd64p32

package syscall
