// mksyscall.pl -l32 -plan9 syscall_plan9.go syscall_plan9_386.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package syscall

func Dup(oldfd int, newfd int) (fd int, err error)

func Open(path string, mode int) (fd int, err error)

func Create(path string, mode int, perm uint32) (fd int, err error)

func Remove(path string) (err error)

func Pread(fd int, p []byte, offset int64) (n int, err error)

func Pwrite(fd int, p []byte, offset int64) (n int, err error)

func Close(fd int) (err error)

func Chdir(path string) (err error)

func Bind(name string, old string, flag int) (err error)

func Mount(fd int, afd int, old string, flag int, aname string) (err error)

func Stat(path string, edir []byte) (n int, err error)

func Fstat(fd int, edir []byte) (n int, err error)

func Wstat(path string, edir []byte) (err error)

func Fwstat(fd int, edir []byte) (err error)
