// mksyscall.pl -l32 -nacl -arm -tags nacl,arm syscall_nacl.go syscall_nacl_arm.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

//go:build nacl && arm
// +build nacl,arm

package syscall

func Exit(code int) (err error)
