// mksyscall.pl -nacl syscall_nacl.go syscall_nacl_amd64p32.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

//go:build amd64p32 && nacl
// +build amd64p32,nacl

package syscall

func Exit(code int) (err error)
