// mksyscall_libc.pl -aix -tags aix,ppc64 syscall_aix.go syscall_aix_ppc64.go
// Code generated by the command above; DO NOT EDIT.

//go:build aix && ppc64
// +build aix,ppc64

package syscall

func Dup2(old int, new int) (err error)

func Getkerninfo(op int32, where uintptr, size uintptr, arg int64) (i int32, err error)

func Listen(s int, backlog int) (err error)

func Shutdown(s int, how int) (err error)

func Openat(dirfd int, path string, flags int, mode uint32) (fd int, err error)

func Acct(path string) (err error)

func Chdir(path string) (err error)

func Chmod(path string, mode uint32) (err error)

func Chown(path string, uid int, gid int) (err error)

func Chroot(path string) (err error)

func Close(fd int) (err error)

func Dup(fd int) (nfd int, err error)

func Faccessat(dirfd int, path string, mode uint32, flags int) (err error)

func Fchdir(fd int) (err error)

func Fchmod(fd int, mode uint32) (err error)

func Fchmodat(dirfd int, path string, mode uint32, flags int) (err error)

func Fchown(fd int, uid int, gid int) (err error)

func Fchownat(dirfd int, path string, uid int, gid int, flags int) (err error)

func Fpathconf(fd int, name int) (val int, err error)

func Fstat(fd int, stat *Stat_t) (err error)

func Fstatfs(fd int, buf *Statfs_t) (err error)

func Ftruncate(fd int, length int64) (err error)

func Fsync(fd int) (err error)

func Getgid() (gid int)

func Getpid() (pid int)

func Geteuid() (euid int)

func Getegid() (egid int)

func Getppid() (ppid int)

func Getpriority(which int, who int) (n int, err error)

func Getrlimit(which int, lim *Rlimit) (err error)

func Getuid() (uid int)

func Kill(pid int, signum Signal) (err error)

func Lchown(path string, uid int, gid int) (err error)

func Link(path string, link string) (err error)

func Lstat(path string, stat *Stat_t) (err error)

func Mkdir(path string, mode uint32) (err error)

func Mkdirat(dirfd int, path string, mode uint32) (err error)

func Mknodat(dirfd int, path string, mode uint32, dev int) (err error)

func Open(path string, mode int, perm uint32) (fd int, err error)

func Pread(fd int, p []byte, offset int64) (n int, err error)

func Pwrite(fd int, p []byte, offset int64) (n int, err error)

func Reboot(how int) (err error)

func Rename(from string, to string) (err error)

func Renameat(olddirfd int, oldpath string, newdirfd int, newpath string) (err error)

func Rmdir(path string) (err error)

func Seek(fd int, offset int64, whence int) (newoffset int64, err error)

func Setegid(egid int) (err error)

func Seteuid(euid int) (err error)

func Setgid(gid int) (err error)

func Setpgid(pid int, pgid int) (err error)

func Setpriority(which int, who int, prio int) (err error)

func Setregid(rgid int, egid int) (err error)

func Setreuid(ruid int, euid int) (err error)

func Setrlimit(which int, lim *Rlimit) (err error)

func Stat(path string, stat *Stat_t) (err error)

func Statfs(path string, buf *Statfs_t) (err error)

func Symlink(path string, link string) (err error)

func Truncate(path string, length int64) (err error)

func Umask(newmask int) (oldmask int)

func Unlink(path string) (err error)

func Uname(buf *Utsname) (err error)
