// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.

// Copyright 2023 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package types

// Aliasは、エイリアス型を表します。
// エイリアス型が作成されるかどうかは、
// GODEBUG環境変数のgotypesalias設定によって制御されます。
// gotypesalias=1の場合、エイリアス宣言はエイリアス型を生成します。
// それ以外の場合、エイリアス情報は型名にのみ存在し、
// 実際の（エイリアスされた）型を直接指します。
type Alias struct {
	obj     *TypeName
	tparams *TypeParamList
	fromRHS Type
	actual  Type
}

// NewAliasは、指定された型名とrhsを持つ新しいAlias型を作成します。
// rhsはnilであってはなりません。
func NewAlias(obj *TypeName, rhs Type) *Alias

func (a *Alias) Obj() *TypeName
func (a *Alias) Underlying() Type
func (a *Alias) String() string

// Unaliasは、tがエイリアス型でない場合はtを返し、
// それ以外の場合はtのエイリアスチェーンを追跡して
// エイリアスでない型に到達すると、その型を返します。
// その結果、返される結果は決してエイリアス型ではありません。
func Unalias(t Type) Type
