// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/instantiate.go

// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// このファイルはジェネリック型の具現化を実装します
// 型パラメータを型引数による置換で行います。

package types

// Instantiateは、型origを与えられた型引数targsでインスタンス化します。
// origはジェネリックな *Alias、*Named、または *Signature 型でなければなりません。
// エラーがない場合、結果のTypeは同じ種類（それぞれ *Alias、*Named、
// または *Signature）のインスタンス化型になります。
//
// *Named型にアタッチされたメソッドもインスタンス化され、元のメソッドと同じ位置を持つが関数スコープがnilの新しい*Funcに関連付けられます。
//
// ctxtがnilでない場合、同じ識別子を持つ以前のインスタンスと重複排除するために使用できます。
// 特別な場合として、ジェネリックの*Signatureの元の型は、ポインタの等価性がある場合のみ同一視されるため、
// 異なる（しかし可能性としては同一の）シグネチャをインスタンス化すると、異なるインスタンスが生成されます。
// 共有されたコンテキストの使用は、同じインスタンスがすべての場合で重複排除されることを保証しません。
//
// validateが設定されている場合、Instantiateは、型origが実際にジェネリックであること、
// 型引数と型パラメータの個数が一致すること、そして型引数がそれぞれの
// 型制約を満たすことを検証します。
// 検証に失敗した場合、結果のエラーは *ArgumentError をラップすることがあり、
// どの型引数がどの理由で型パラメータ制約を満たさなかったかを示します。
//
// validateが設定されていない場合、Instantiateはorigがジェネリックかどうかの確認、
// 型引数の個数検証、または型引数が制約を満たすかどうかの確認を行いません。
// この場合、Instantiateはエラーを返さないことが保証されますが、panicする可能性があります。
// 具体的には、*Signature型では型引数の個数が不正な場合に即座にpanicし、
// *Named型では *Named API の内部で後からpanicが発生することがあります。
func Instantiate(ctxt *Context, orig Type, targs []Type, validate bool) (Type, error)
