name: godoc
on:
  pull_request:
  push:

jobs:
  godoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: |
          set -uexo pipefail
          go list ./... | xargs -n1 go doc -all > /dev/null
