name: godoc
on:
  pull_request:
  push:

jobs:
  godoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - run: |
          set -uexo pipefail
          gotip list ./... | xargs -n1 gotip doc -all > /dev/null
