name: sync
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - release-branch.go1.27
          - release-branch.go1.26
          - release-branch.go1.25
    permissions:
      contents: write

    steps:
      - name: checkout tools
        uses: actions/checkout@v6
        with:
          path: tools

      - uses: actions/setup-go@v6
        with:
          go-version-file: ./tools/_tools/go.mod
          cache-dependency-path: ./tools/_tools/go.mod
      - name: install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - name: install tools
        working-directory: ./tools/_tools
        run: |
          gotip install ./importgodoc

      - name: checkout std
        uses: actions/checkout@v6
        with:
          ref: upstream/${{ matrix.branch }}
          path: std

      - name: checkout golang/go
        uses: actions/checkout@v6
        with:
          repository: golang/go
          ref: ${{ matrix.branch }}
          path: go

      - name: sync
        env:
          BRANCH_NAME: upstream/${{ matrix.branch }}
        working-directory: ./std
        run: |
          "$GITHUB_WORKSPACE/tools/_tools/rm-all.sh"
          importgodoc "$GITHUB_WORKSPACE/go/src" "$GITHUB_WORKSPACE/std"

      - name: commit
        uses: shogo82148/actions-commit@v1
        with:
          base-branch: upstream/${{ matrix.branch }}
          working-directory: ./std
